name: fastcam_flutter_beamin
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  # 페이지 이동을 위한 패키지
  go_router: ^13.2.0
  # 상태관리를 위한 패키지
  flutter_riverpod: ^2.4.10
  # 이미지 픽커를 위한 패키지
  google_sign_in: ^6.2.1
  # 숫자 포메팅을 위한 패키지
  intl: ^0.19.0
  # 상단 배너를 위한 패키지
  dots_indicator: ^3.0.0
  # immutatability를 갖는 클래스를 쉽게 만들어주는 패키지
  freezed_annotation: ^2.4.1
  # json 변환을 위한 패키지
  json_annotation: ^4.8.1
  # image 압축을 위한 패키지
  flutter_image_compress: ^2.1.0
  # firebase 관련 패키지
  firebase_core: ^2.24.2
  firebase_auth: ^4.17.7
  firebase_storage: ^11.6.8
  cloud_firestore: ^4.4.3
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/
